version: 0.2
phases:
  install:
    runtime-versions:
       java: corretto17
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install maven -y 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started 
      - mvn clean package  
artifacts:
  files:
    - webapp/target/webapp.war
  discard-paths: yes
