version: 0.2
phases:
  install:
    runtime-versions:
       java: corretto17
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install maven -y 
  build:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    commands:
      - echo Entered the build phase...
      - echo Build started 
      - mvn clean package
      - echo Build started for Docker
      - echo Building the Docker image...          
      - docker build -t dockervicky:latest .
      - docker tag dockervicky:latest 034359045621.dkr.ecr.ap-southeast-1.amazonaws.com/dockervicky
  post_build:
    commands:
      - echo Build completed 
      - echo Pushing the Docker images...
      - docker push 034359045621.dkr.ecr.ap-southeast-1.amazonaws.com/dockervicky
   
artifacts:
  files:
    - webapp/target/webapp.war
  discard-paths: yes
