version: 0.2
phases:
  install:
    runtime-versions:
       java: corretto17
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install maven -y 
      - apt-get install docker -y
  pre_build:
    commands:
      - echo Entered the build phase...
      - echo Build started 
      - mvn clean package
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION 
      - echo Build started for Docker
      - echo Building the Docker image...          
      - docker build -t dockervickytomcat:latest .
      - docker tag dockervickytomcat:latest 034359045621.dkr.ecr.ap-southeast-1.amazonaws.com/vickyrepo
  post_build:
    commands:
      - echo Build completed 
      - echo Pushing the Docker images...
      - docker push 034359045621.dkr.ecr.ap-southeast-1.amazonaws.com/vickyrepo
artifacts:
  files:
    - webapp/target/webapp.war
  discard-paths: yes
