version: 0.2

phases:
  build:
    commands:
      - echo Build started 
      - mvn clean install package
  post_build:
    commands:
      - echo Build completed Successfully
artifacts:
  files:
    - target/webapp.war
  discard-paths: yes
