version: 0.2
phases:
  install:
    runtime-versions:
       java: corretto17
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - apt-get update -y
    finally:
      - echo This always runs even if the update or install command fails  
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started 
      - mvn clean package
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed 
artifacts:
  files:
    - target/webapp.war
  discard-paths: yes
