version: 0.2
phases:
  install:
    runtime-versions:
       java: corretto17
    commands:
      - echo Entered the install phase...
      - yum update -y
      - yum install maven -y
      - mvn --version
    finally:
      - echo This always runs even if the update or install command fails  
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started 
      - mvn clean package 
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed 
artifacts:
  files:
    - target/webapp.war
  discard-paths: yes
